// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPDq8-NiJppvqoAMAhqRtlYhw_w-m1UI8',
    appId: '1:230753965139:web:4d0ad936f5654815f1a2a6',
    messagingSenderId: '230753965139',
    projectId: 'smartprint-50c22',
    authDomain: 'smartprint-50c22.firebaseapp.com',
    storageBucket: 'smartprint-50c22.firebasestorage.app',
    measurementId: 'G-X0RPPWLYDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByiUpdK75x052p11TEWeuqsGYBgN8jSJM',
    appId: '1:230753965139:android:a24f0b4ea99a335bf1a2a6',
    messagingSenderId: '230753965139',
    projectId: 'smartprint-50c22',
    storageBucket: 'smartprint-50c22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzZftKJLyf69EecrEsELp4H1wswoXr6YU',
    appId: '1:230753965139:ios:db492957f3624c1df1a2a6',
    messagingSenderId: '230753965139',
    projectId: 'smartprint-50c22',
    storageBucket: 'smartprint-50c22.firebasestorage.app',
    iosBundleId: 'com.example.smartprint',
  );
}
